### ISSUE TITLE
Deprecated on PHP 8.1.11: Calling end() on an object

### ISSUE THREAD

**Issue by aleixpellicer** [ThingEngineer/PHP-MySQLi-Database-Class#1001]
Not working in 8.1.11:

`Deprecated: end(): Calling end() on an object is deprecated in X:\UniServerZ_15\vhosts\vatiometrogiovanni\vendor\thingengineer\mysqli-database-class\MysqliDb.php on line 1675`

Having to go back to php 7 in order to work

**Comment by SilverOkami42** [comment]
I found a quick fix was to replace `end($result)` with `$result->{array_key_last((array)$result)}`

**Comment by SilverOkami42** [comment]
I also discovered changing line 2058 to `$val = $vals[$i++] ?? null;` fixed it finding a array value that didn't exist.

**Comment by RivenSkaye** [comment]
> I also discovered changing line 2058 to `$val = $vals[$i++] ?? null;` fixed it finding a array value that didn't exist.

This sounds like there are fewer elements in the array than question marks in the query. Granted, it'd be better to check that, but that should be a separate issue.
