### ISSUE TITLE
Error inserting data

### ISSUE THREAD

**Issue by khantry** [ThingEngineer/PHP-MySQLi-Database-Class#1002]
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/db/vendor/joshcam/mysqli-database-class/MysqliDb.php on line 1838

 $this->_query .= ' (`' . implode('`, `', $dataColumns) . '`) ';
$this->_query .= ' (`' . implode($dataColumns, '`, `') . '`) ';

**Comment by s-vhs** [comment]
Data should be inserted. This is just an error it gives for some reason. I recommend implementing a debug-mode which you can turn off in production.

**Comment by RivenSkaye** [comment]
This seems weird to say the least. `$datacolumns` _is_ the array there, with ``'`, `'`` being the glue string. The order is already correct as it stands, which makes me wonder if the parser is having problems with the mess of backticks and single quotes

**Comment by avbdr** [comment]
this is fixed in latest version
