### ISSUE TITLE
how show a sql query ?

### ISSUE THREAD

**Issue by khanhnam99** [ThingEngineer/PHP-MySQLi-Database-Class#1004]
how show a sql query ?

**Comment by s-vhs** [comment]
By using the `getLastQuery()` function.

```php
$conn = new MysqliDb("localhost", "root", "root", "testDb"); // create new connection
$username = $conn->escape($_GET["username"]); // get username to get users by
$result = $conn->orderBy("id", "DESC")->where("username", "%" . $username . "%", "like")->get("users"); // get users from db
//print_r($result); // gives out our result
echo $conn->getLastQuery(); // gets last executed query in SQL format
```

This should be the proper way to use it. As an example, I selected a few users with a `LIKE` and `ORDER BY` condition. You can use whatever query and variable for the connection you want, just use, after execution of the query, the `getLastQuery()` function.

I hope I was of help :)

**Comment by khanhnam99** [comment]
Great! thanks
