### ISSUE TITLE
DISTINCT?

### ISSUE THREAD

**Issue by s-vhs** [ThingEngineer/PHP-MySQLi-Database-Class#1008]
Hey, it's me once again. I've noticed another function that is missing and possibly would be a great addition: the `DISTINCT` parameter.

Here's the W3Schools article about it: https://www.w3schools.com/Sql/sql_distinct.asp

Maybe you'll implement this in the near future as well :)

Also, happy new year!

**Comment by adrianlaraperez88** [comment]
You can add it in select I use it a lot and working fine !!

**Comment by s-vhs** [comment]
Can you give me some kind of example please? I am a little confused and got errors when I tried it...

**Comment by s-vhs** [comment]
You you mean like this?
`$conn->orderBy("timestamp", "DESC")->get("blogs_entries", 5, "DISTINCT blog");`

**Comment by s-vhs** [comment]
Yeah. After testing it worked just like that. Thanks!
