### ISSUE TITLE
php 8.2 error

### ISSUE THREAD

**Issue by codephp1999** [ThingEngineer/PHP-MySQLi-Database-Class#1016]
please fix it
str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated in ...MysqliDb.php on line 2354

**Comment by BataBoom** [comment]
```
$currentDatetime = Carbon::now();
Error Query: $db->rawQuery("SELECT * FROM `am_store` WHERE `expires` < ".$currentDatetime->toDateTimeString());
Temporary Fix Query: $db->rawQuery("SELECT * FROM `am_store` WHERE `expires` < "."'".$currentDatetime->toDateTimeString()."'"); 
```
php verison 8.2.10
DEPRECATED  str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated in vendor/thingengineer/mysqli-database-class/MysqliDb.php on line 559.

mysqli_sql_exception 

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '  05:00:56' at line   1

at vendor/thingengineer/mysqli-database-class/MysqliDb.php:1995
