### ISSUE TITLE
wrong implode function parameters

### ISSUE THREAD

**Issue by nathanaelmemis** [ThingEngineer/PHP-MySQLi-Database-Class#1019]
MysqliDb.php, line 1838:
$this->_query .= ' (`' . implode($dataColumns, '`, `') . '`) ';

should be

$this->_query .= ' (`' . implode('`, `', $dataColumns) . '`) ';

note: this is for the last release

**Comment by decMuc** [comment]
I find this surprising. I have an insert statement in two different classes – it works in one class, but in the other, I encounter an error in the exact same line. When I swap the line between the classes, it now works in the previously problematic class. I just can't comprehend why it works in one class while being nearly identical to the other.

**Comment by ThingEngineer** [comment]
I missed this issue when I merged a fix from a duplicate issue. 
Fixed in Merge pull request #1028
