### ISSUE TITLE
Master Slave database

### ISSUE THREAD

**Issue by mshs013** [ThingEngineer/PHP-MySQLi-Database-Class#1029]
How can I use master-slave database? I want to write data using master DB and read data using slave DB. Anyone can help me to do this?

**Comment by ThingEngineer** [comment]
What you are looking for is [MySQL Replication](https://hevodata.com/learn/mysql-master-slave-replication/).
The exact implementation method  is very dependent on your specific application needs, but this should get you started in the right direction. 


Interesting implementation worth diving into considering this is a PHP library. [[php-mysql-replication](https://github.com/krowinski/php-mysql-replication)](https://github.com/krowinski/php-mysql-replication)
