### ISSUE TITLE
Packagist / ThingEngineer / JoshCam  inconsistencies 

### ISSUE THREAD

**Issue by iahim** [ThingEngineer/PHP-MySQLi-Database-Class#1031]
Hello, 
### Is it possible to somehow define which packagist project is the correct one, and maybe keep only one?
On `https://packagist.org/packages/thingengineer/mysqli-database-class`  we are still at version 2.9.3.
On `https://packagist.org/packages/joshcam/mysqli-database-class`  we are at 2.9.4  

On _joshcam_ packagist in the documentation is mentioned to use `composer require thingengineer/mysqli-database-class`.

On the `MysqliDb.php` file the _`@version`_  is still  **2.9.3** (even though the file is from 2.9.4)

Many thanks again for a great module!

**Comment by ThingEngineer** [comment]
My apologies I forgot that Packagist was not auto-updated. It is updated now and I added a todo to setup a hook to keep it updated.

[thingengineer](https://packagist.org/packages/thingengineer/mysqli-database-class) is the correct project.

Thanks Mike @iahim and you're very welcome!

**Comment by iahim** [comment]
@ThingEngineer  many thanks for updating the package and for creating it!  Chapeau!
