### ISSUE TITLE
many errors in code

### ISSUE THREAD

**Issue by auth1299** [ThingEngineer/PHP-MySQLi-Database-Class#1033]
There is many issues with this script. The undefined variable being the worse error. What IDE are you guys using to manipulate this script? 

![image](https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/assets/7773605/fb2e5714-dc30-4601-a19c-c01ab5ecab5e)

**Comment by BataBoom** [comment]
the package had a nice run, I switched to https://github.com/catfan/Medoo

**Comment by RivenSkaye** [comment]
Cannot reproduce in an updated vscode running PHP @ latest
![image](https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/assets/14993038/a7e1e165-d79a-4d07-b484-880436658022)

Have you made sure to grab [the latest release](https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/releases/tag/v2.9.4) or did you make any local modifications? It might be worth checking the diff between them as it works for me in a production environment.
