### ISSUE TITLE
How update column updateDate , value is null

### ISSUE THREAD

**Issue by khanhnam99** [ThingEngineer/PHP-MySQLi-Database-Class#1035]
How update column updateDate , value is null

use mysql 8
Incorrect date value: '' for column 'updateDate ' at row 1

$data = [
        'updateDate ' =>  null
    ];
$db->update('TB_DISCOUNT', $data)

echo $db->getLastQuery();

// show query
// UPDATE TB_DISCOUNT `updateDate` = 'NULL'

how show query result like this:
UPDATE TB_DISCOUNT SET  `updateDate` = NULL

**Comment by avbdr** [comment]
this no
