### ISSUE TITLE
I would like a rawData for updates.

### ISSUE THREAD

**Issue by kennylajara** [ThingEngineer/PHP-MySQLi-Database-Class#175]
Hi, 

I would like to make an update where I can set a column value equal to another column value. Below, I give you an example in which I would like to be able to establish the value of the 'maxscore' column equal to the 'currentScore' column:

```
$data = Array (
    'maxScore = currentScore',    // HERE IS THE IMPORTANT PART
);
$db->where ('id', 1);
$db->update ('users', $data);
```

Thus would not need to make 2 querys. Just a simple update.

**Comment by SanMane** [comment]
Do this; One query :smiley: 
```php
$db->where ('id', 1)->update ('users', $data);
```

**Comment by avbdr** [comment]
this will work. But i agree, raw line will be more easy to ready in such cases.
```
$data = Array (
    'maxScore' => $db->func('currentScore'),
);
$db->where ('id', 1);
$db->update ('users', $data);
```

**Comment by thingNumber1** [comment]
Thanks. 

Now I have a similar question: what if I need to put the same number plus one, do I need to do tow querys?

cant I do something like this (?):

	$data = array(
		'lvl' => $db->func('lvl'+1),
	);
	$db->where('id', 1);
	$db->update('character', $data);
