### ISSUE TITLE
Support for php 5.3.0 broken

### ISSUE THREAD

**Issue by FlickerBean** [ThingEngineer/PHP-MySQLi-Database-Class#684]
composer.json claims there is support for php 5.3.0 which to my knowledge there was, and worked perfectly up until commit 8e750e65e99c5c85f39c6f356b2ea9e83a473b41

The shorthand array usage here forces php 5.4.

Either the shorthand array usage should be removed, or composer.json should be updated.

Personally i'm all for bumping php version requirements if it's justified, however if the only benefit gained is use of shorthand syntax, i'm not sure it's worth it.

**Comment by avbdr** [comment]
this is  were fixed
