### ISSUE TITLE
Issue with 2.9 release

### ISSUE THREAD

**Issue by premento** [ThingEngineer/PHP-MySQLi-Database-Class#699]
I updated my project with 2.9 release and i suddenly started getting thing error.

*564 FastCGI sent in stderr: "PHP message: Undefined property: MysqliDb::$_transaction_in_progress" while reading response header from upstream

**Comment by premento** [comment]
I have added `protected $_transaction_in_progress = false;` to mysqlidb.php and it worked fine. Not sure whether its correct or not.

**Comment by avbdr** [comment]
thank you! Fixed and pushed 2.9.1 bugfix release for that
