### ISSUE TITLE
Error in simple select query

### ISSUE THREAD

**Issue by ameetpawar00** [ThingEngineer/PHP-MySQLi-Database-Class#709]
`$db->where("status","0");
					$db->where("delete","0");
					$employee = $db->get("employee");`

just a select query giving fatal error;

Fatal error: Uncaught Exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'delete = ?' at line 1 query: SELECT * FROM employee WHERE status = ? AND delete = ? in /var/www/live/app/app.talentedindia.co.in/html/control/include/MysqliDb.php:1841 Stack trace: #0 /var/www/live/app/app.talentedindia.co.in/html/control/include/MysqliDb.php(1449): MysqliDb->_prepareQuery() #1 /var/www/live/app/app.talentedindia.co.in/html/control/include/MysqliDb.php(619): MysqliDb->_buildQuery(NULL) #2 /var/www/live/app/app.talentedindia.co.in/html/control/include/viewUser.php(83): MysqliDb->get('employee') #3 /var/www/live/app/app.talentedindia.co.in/html/control/viewUser.php(19): include('/var/www/live/a...') #4 {main} thrown in /var/www/live/app/app.talentedindia.co.in/html/control/include/MysqliDb.php on line 1841 

//// please help

**Comment by siberfx** [comment]
use the whole query as in Chain system.
and for the "where" queries try to use it as integer

$employee = $db->where("status",0)->where("delete",0)->$db->get("employee");
