### ISSUE TITLE
Fatal error: after update mysql from 5.6 to  5.7.21

### ISSUE THREAD

**Issue by hosamalzagh** [ThingEngineer/PHP-MySQLi-Database-Class#719]
i see Fatal error: after update mysql from 5.6 to  5.7.21 cpanel

Fatal error: Uncaught Exception: Problem preparing query (SELECT distinct t.lyric_id FROM top t LEFT JOIN duet d on d.lyric_id = t.lyric_id WHERE d.singer_id = ? AND d.lyric_id IS NOT NULL ORDER BY t.reading DESC LIMIT 5) Expression #1 of ORDER BY clause is not in SELECT list, references column 'xpredo_lyrics.t.reading' which is not in SELECT list; this is incompatible with DISTINCT in /home//public_html/core/function/MysqliDb.php:1486 Stack trace: #0 /home//public_html/core/function/MysqliDb.php(1099): MysqliDb->_prepareQuery() #1 /home//public_html/core/function/MysqliDb.php(550): MysqliDb->_buildQuery(5) #2 /home//public_html/core/function/func.php(144): MysqliDb->get('top t', 5, 'distinct t.lyri...') #3 /home//public_html/lyric.php(137): func->top_get('lyric_id', 5, 1) #4 {main} thrown in /home//public_html/core/function/MysqliDb.php on line 1486

**Comment by avbdr** [comment]
error doesnt seems to be related to mysqlidb

**Comment by hosamalzagh** [comment]
$this->db->join("duet d", "d.$val = t.$val", "left");
        $this->db->where("d.singer_id",$where);
        $this->db->where("d.$val ",NULL, 'IS NOT');
        $this->db->orderBy('t.reading',"desc");
        return $this->db->get('top t', $limite, "distinct t.$val");

this code work on mysql 5.6 put not work on 5.7

error from mysqlidb

**Comment by hosamalzagh** [comment]
i fix it by add 
sql-mode="NO_ENGINE_SUBSTITUTION"
in my   my.cnf
