### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by temamagic** [ThingEngineer/PHP-MySQLi-Database-Class#722]
What I do:
`$chat = $db->where('chat_id', $message->chat['id'])->getOne('groups');`

I got results with my chat, ex:

> Array
> (
>     [chat_id] => -232509812
>     [chat_title] => test
>     [chat_type] => group
> )

And its ok. BUT after (on next row in code) I do this:
`$db->where('chat_id', $message->chat['id'])->update('groups', ['chat_id', $message->migrate_to_chat_id]);`

And I get error: 

> Unknown column '0' in 'field list' query: UPDATE groups SET `0` = ?, `1` = ? WHERE  chat_id = ?

**Comment by temamagic** [comment]
![image](https://user-images.githubusercontent.com/15264697/36636993-fef430aa-19e2-11e8-9650-3745e21c91fe.png)
![image](https://user-images.githubusercontent.com/15264697/36637001-0e67437e-19e3-11e8-84b9-508358346f01.png)

wtf?

**Comment by siberfx** [comment]
show more spesific code, and try to explain what exactly you want to do ? I may help you.

**Comment by temamagic** [comment]
@siberfx thats all code. I trying to update row where chat_id == -232509812 and set chat_id to new value

**Comment by ricwein** [comment]
I guess the error is in your update-call. The given dataset should be an associative array, where the key explains which db-attribute should be set. So replacing the `,` with a `=>` should do the trick.

So the correct call should be:
```php
$db->where('chat_id', $message->chat['id'])->update('groups', ['chat_id' => $message->migrate_to_chat_id]);
```

**Comment by siberfx** [comment]
and I also would like to have a selfi with mikhail bashkatov from Kuhnya serial :)

**Comment by temamagic** [comment]
@ricwein Thank you so much!
I did not notice this comma, and I thought everything was fine.

Thanks again!
