### ISSUE TITLE
Fatal error: Uncaught exception 'ReflectionException' with message 'Class mysqli does not exist'

### ISSUE THREAD

**Issue by cr1zz** [ThingEngineer/PHP-MySQLi-Database-Class#726]
When I try to call the class via '**php -f script.php**' on the linux shell, I'm getting the following error:

`PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class mysqli does not exist' in .../inc/inc.mysqli.php:294
Stack trace:
#0 .../inc/inc.mysqli.php(294): ReflectionClass->__construct('mysqli')
#1 .../inc/inc.mysqli.php(377): MysqliDb->connect('default')
#2 .../inc/inc.mysqli.php(1908): MysqliDb->mysqli()
#3.../inc/inc.mysqli.php(1519): MysqliDb->_prepareQuery()
#4 .../inc/inc.mysqli.php(686): MysqliDb->_buildQuery(NULL)
#5 script.php(19): MysqliDb->get('devices')
#6 {main}
  thrown in .../inc/inc.mysqli.php on line 294`

**Include via:**
`
// get basedir
    $basedir = dirname(dirname(__FILE__)). '/';
    
    // Includes
    include $basedir.'inc/inc.functions.php';    

    // MySQL Verbindung aufbauen
  	require $basedir."/inc/inc.mysqli.php";
  	$db = new MysqliDb ('...:...', '...', '...', '...');`

**Comment by nilsgraustins** [comment]
I got the same errror calling Joomla project via php execution method. (safe from hacking Joomla) and got the same error. Seems, it is not related to this project/class. I mean, this is a php level error .
