### ISSUE TITLE
How to build orWhere better?

### ISSUE THREAD

**Issue by dungla2011** [ThingEngineer/PHP-MySQLi-Database-Class#727]
I want to build this:

SELECT *  FROM abc WHERE id= 1 AND **(field1 = 0 OR field2 = 0)**

- if it possible with ?
$db->where ?
$db->orWhere ?

**I try:**
$db->where("id", "1");
$db->where("field1", "0");
$db->orWhere("field2", "0");
$db->get("abc");

--> it return:
SELECT *  FROM abc WHERE id= 1 AND **field1 = 0 OR field2 = 0**

It is not my need,
So It must use Raw query in this case?

**Comment by siberfx** [comment]
check sub queries.

**Comment by avbdr** [comment]
think rawQuery is your friend :)

**Comment by slash-zero** [comment]
Subqueries are the devil, if not used properly. 

Seriously though, just use a rawQuery instead.

**Comment by dungla2011** [comment]
oh, I found solution quickly after asking:

SELECT * FROM abc WHERE id= 1 AND (field1 = 0 OR field2 = 0)
<=> 
$db->where("id", "1");
$db->where("field1 = 0 OR field2 = 0");
$db->get("abc");

It's simple, in document :)

Thank the author !
