### ISSUE TITLE
dbObject ->Save() does nothing

### ISSUE THREAD

**Issue by momoelz** [ThingEngineer/PHP-MySQLi-Database-Class#730]
just as the title says ist i tried to use the dbObject function but it does not store the values into database:

	protected function verify() {
			$id = $this->request['id'] ? strtolower (trim($this->request['id'])) : '';
			$mail_check = account_verification::where('hash',$id)->where('status',0)->orderBy('timestamp','DESC')->getOne();
			if($mail_check) {
				$mail_check->status = 1;
				$mail_check->save();
				header("Location: http://imochs.com/verify-success");
				die();
			}
			header("Location: http://imochs.com");
			die();
			return(true);
		}

**Comment by m4xw** [comment]
You should post your Schema FIle

**Comment by momoelz** [comment]
Sorry for my Noobness, I dont know what you mean by Schema File, do you mean the dbObject file i created? 

<?php
	class account_verification extends dbObject {
		
	}
?>

or do you want to see the mysql structure?

[account_verification_structure.pdf](https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/files/1799189/account_verification_structure.pdf)

**Comment by m4xw** [comment]
Sry for the late answer.
You don't define a table, nor a primary key, it won't work like that.

You should at least add

protected $dbTable    = "<table name>";
protected $primaryKey = "<primary key>";`

You might need to add $dbFields too, depending on what u need/want to do (it will only save fields defined in them, unless u change the source).

**Comment by momoelz** [comment]
thanks that worked out :)
