### ISSUE TITLE
Pagination - orderBy

### ISSUE THREAD

**Issue by usafkirkland** [ThingEngineer/PHP-MySQLi-Database-Class#732]
Hi, great class.  I am trying to submit an orderBy in pagination but it doesn't seem to make any difference.  Is there a way to add an orderBy in pagination?

**Comment by usafkirkland** [comment]
in short:
$db->where('active', 1);
$db->having('category_id', 3);
$db->orderBy("name","asc");
$db->pageLimit = 6;
$db->arraybuilder()->paginate("tec_products",1);

**Comment by siberfx** [comment]
have you tried orderBy with an integer (int) value instead of a string?

**Comment by usafkirkland** [comment]
I just did to see if it would adjust.  Everything fires correctly, except for the orderBy part.

**Comment by usafkirkland** [comment]
I had an issue with my function passing a variable.  There is nothing wrong with the classes pagination function.  Thank you for the quick response!
