### ISSUE TITLE
return id insert() type varchar

### ISSUE THREAD

**Issue by hoangnamitc** [ThingEngineer/PHP-MySQLi-Database-Class#735]
Hi guy,

I have table, column id type varchar. After run $id = $db->insert();
$id not return id value that return 1.
So how to get value id (type is varchar) ?

tks !

**Comment by hemaantjd** [comment]
change id type to int and make it primary + auto increamented

**Comment by hoangnamitc** [comment]
I know that, but for some reason I want id to be the varchar type and I want to get that id when inserting :(
If id is a string type then it works fine !

**Comment by user745** [comment]
MySQL doesn’t support auto-incrementation of types other than int (understandably) so it won’t be generating an automatic id for that. If you must have a varchar id you’ll have to generate one yourself (randomly?), then check to make sure it doesn’t already exist in your table, and then insert it as a regular data column

**Comment by F-V** [comment]
Just picking up on this topic. In some cases one would have a non generated (AI) primary key e.g. when using UID's as ID. As stated before, that would give a 1 as returned int.

In said case you world override the return value with the id you used to generate the record.

```
$db = MysqliDb::getInstance();
$account['ID']="someGUID";
$account['Email']="test@example.com";
$result = $db->insert("table",$account);
//if the result is 1, then just replace the id with the one you chose
if($result){
   return $account['ID'];
}
return $result;
```
