### ISSUE TITLE
Install this package with Composer then find a hidden directory named "".git" in Vendor directory, Can you remove it ?

### ISSUE THREAD

**Issue by getchu** [ThingEngineer/PHP-MySQLi-Database-Class#738]
Install this package with Composer then find a hidden directory named "".git" in Vendor directory, Can you remove it ?

通过Composer安装这个软件包，然后在Vendor目录中找到“.git”隐藏目录，你可以删除它吗？

このパッケージをComposerにインストールし、Vendorディレクトリに ".git"という名前の隠しディレクトリを見つけてください。削除できますか？

git add ./
git common -m "add database libraray"
git push origin develop
...........What ? git add failure ?? Oh, ".git" Folder nesting

**Comment by avbdr** [comment]
https://stackoverflow.com/questions/25981292/how-to-make-composer-not-create-a-git-directory-for-a-package
