### ISSUE TITLE
changing public "count" variable on DELETE

### ISSUE THREAD

**Issue by shuriks83** [ThingEngineer/PHP-MySQLi-Database-Class#739]
I added 
$this->count = $stmt->affected_rows 
in update public function on :859

**Comment by canarslan12** [comment]
It might break older applications in same cases. But returning affected rows when deleting will be better imo.

**Comment by VonHirsch** [comment]
I agree with this modification, and IMO it shouldn't break anyone if their code is clean?  I mean they shouldn't trust a dirty $count anyway right?

**Comment by VonHirsch** [comment]
Created PR https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/pull/750

**Comment by avbdr** [comment]
I think we can merge this one. After I looked at it one more time, there no
behavior change here.

**Comment by avbdr** [comment]
merged thanks.
