### ISSUE TITLE
connect too time  error

### ISSUE THREAD

**Issue by zhaoyangwu** [ThingEngineer/PHP-MySQLi-Database-Class#742]
mysqli::prepare(): MySQL server has gone away in /data/wwwroot/warmlight_service/src/App/Vendor/Db/MysqliDb.php line 1908

**Comment by zhaoyangwu** [comment]
Error while sending STMT_PREPARE packet. PID=18622 in /data/wwwroot/warmlight_service/src/App/Vendor/Db/MysqliDb.php line 1908

**Comment by getchu** [comment]
使用 try catch 捕获异常
[http://www.php.net/manual/en/class.mysqli-sql-exception.php](http://www.php.net/manual/en/class.mysqli-sql-exception.php)

mysqli_report(MYSQLI_REPORT_STRICT);

$driver = new mysqli_driver();
$driver->report_mode = MYSQLI_REPORT_ALL;
$driver->report_mode = MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT;
[http://php.net/manual/en/mysqli-driver.report-mode.php](http://php.net/manual/en/mysqli-driver.report-mode.php)

**Comment by getchu** [comment]
edit your mysql config file
my.cnf 

#connect_timeout=31536000

wait_timeout=31536000
interactive_timeout=31536000

**Comment by avbdr** [comment]
you can use autoreconnect to bypass this error.
