### ISSUE TITLE
Compatibility problem : order by field (fieldName, "Chinese string 1", "Chinese string 2")

### ISSUE THREAD

**Issue by getchu** [ThingEngineer/PHP-MySQLi-Database-Class#748]
public function orderBy($orderByField, $orderbyDirection = "DESC", $customFieldsOrRegExp = null)

        if (is_array($customFieldsOrRegExp)) {
            foreach ($customFieldsOrRegExp as $key => $value) {
                $customFieldsOrRegExp[$key] = preg_replace("/[^-a-z0-9\.\(\),_` ]+/i", '', $value);
            }
            $orderByField = 'FIELD (' . $orderByField . ', "' . implode('","', $customFieldsOrRegExp) . '")';
        }elseif(is_string($customFieldsOrRegExp)){
	    $orderByField = $orderByField . " REGEXP '" . $customFieldsOrRegExp . "'";

But !!!!!!!!!!!!!!!!!!!!!!!!!!!!
$db->orderBy( 'type', 'ASC', array(
    '你好',
    '世界'
));
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
preg_replace ????????????????????????

**Comment by avbdr** [comment]
this should be resolved in master
