### ISSUE TITLE
How to group the Where condition

### ISSUE THREAD

**Issue by r94ever** [ThingEngineer/PHP-MySQLi-Database-Class#752]
Hi all,

I have a query which is not very complex, and although I can solve it by using RAW query, but I would like to know there are other solutions or not.

My raw query is:

`SELECT SQL_CALC_FOUND_ROWS * FROM b1h5p6_staffs s  JOIN b1h5p6_positions p on p.ID = s.position  JOIN b1h5p6_branches b on b.ID = s.branch WHERE  s.status = 'activated'  AND s.gender = 'male'  AND s.branch = '1'  AND ( s.username LIKE '%ivan%'  OR s.firstName LIKE '%ivan%'  OR s.lastName LIKE '%ivan%'  OR s.email LIKE '%ivan%'  OR s.website LIKE '%ivan%'  OR s.mobile LIKE '%ivan%'   ) ORDER BY s.ID ASC  LIMIT 0, 10`

The problem is the `(` and `)` characters. If I code like this:

```
$db->where( 's.username, '%' . 'ivan' . '%', 'LIKE' )
      ->where( 's.status , 'activated' )
      ->where( 's.gender, . 'male'  )
      ->where( 's.branch, '1' )
      ->orWhere( 's.firstName, '%' . 'ivan' . '%', 'LIKE' )
      ->orWhere( 's.lastName, '%' . 'ivan' . '%', 'LIKE' )
      ->orWhere( 's.email, '%' . 'ivan' . '%', 'LIKE' )
      ->orWhere( 's.website, '%' . 'ivan' . '%', 'LIKE' )
      ->orWhere( 's.mobile, '%' . 'ivan' . '%', 'LIKE' )
```

it will have no `(` and `)` characters in the real query, which are very strong as the filters of my search box. Thank for any help!

**Comment by r94ever** [comment]
Thanks but as I said. I would like to look for a solution without Raw query

**Comment by siberfx** [comment]
As i understand, you want queries with 'and' right?

Selim GORMUS - Asus zenfone 2

**Comment by siberfx** [comment]
Also check about sub querying for the query you gaved i see it also needed

Selim GORMUS - Asus zenfone 2

**Comment by r94ever** [comment]
No. I mean 

SELECT * FROM table WHERE 1st condition AND 2nd condition AND ( 3rd condition OR 4th condition OR 5th condition )

**Comment by ricwein** [comment]
You can write custom conditions for where-statements like this:

```php
$searchVar = 'ivan';
$db->where('s.username', '%' . $searchVar . '%', 'LIKE')
    ->where('s.status', 'activated')
    ->where('s.gender', 'male')
    ->where('s.branch', '1')
    ->where('(s.firstName LIKE ? OR s.lastName LIKE ? OR s.email LIKE ? OR s.website LIKE ? OR s.mobile LIKE ?)', Array(
        '%' . $searchVar . '%', '%' . $searchVar . '%', '%' . $searchVar . '%', '%' . $searchVar . '%', '%' . $searchVar . '%'
    ));
```

P.s.: Also

**Comment by r94ever** [comment]
It worked like a charm. Thanks so much
