### ISSUE TITLE
How to assign select subquery AS column alias?

### ISSUE THREAD

**Issue by mattjis** [ThingEngineer/PHP-MySQLi-Database-Class#757]
`SELECT *, (SELECT username FROM users WHERE id = places.user_id) AS username FROM places
`

How can something like this be possible with this class?

Not with a raw query my other queries are much more complex than this.

**Comment by avbdr** [comment]
Unfortunately I had no time to add subquery support to insert() 
So it is not possible for now.

**Comment by avbdr** [comment]
Ups, it's an answer to a different ticket

**Comment by mattjis** [comment]
@avbdr wrong ticket? Do you whether or not what I'm trying to do is possible?
