### ISSUE TITLE
Does this automatically take care of SQL injection while preparing quries?

### ISSUE THREAD

**Issue by mianaliasjad** [ThingEngineer/PHP-MySQLi-Database-Class#764]
i want to ask does this DB class Use prepared statements and parameterized queries to prevent SQL injections?

**Comment by ricwein** [comment]
Hey.
In short terms: **yes**, this class uses prepared statements with placeholders for safe variable-bindings.

Please also take a look at previous issues before asking next time 😉:
- [**#508** Protected with SQL injection ?](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/508)
- [**#408** SQL Injection, question.](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/408)
- [**#400** Is it usefull for Prevent Sql injection?](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/400)
- [**#174** Is this class prevent common security vulnerabilities: SQL injection, XSS, CSRF etc](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/174)

**Comment by mianaliasjad** [comment]
oh thanks <3
