### ISSUE TITLE
Delete function always return true

### ISSUE THREAD

**Issue by jsharma44** [ThingEngineer/PHP-MySQLi-Database-Class#766]
Hello. Recently when I tried delete an item. It always return true no matter what I'd exsist or not.
$db->where('id', 1);
$delete = $db->delete('users')
It always return true. 

How to check it properly?

**Comment by siberfx** [comment]
Use try catch to understand if the query properly working or not, i have not experienced such issue at all

**Comment by VeNoMouS** [comment]
```    return ($stmt->affected_rows > -1);	//	affected_rows returns 0 if nothing matched where statement, or required updating, -1 if error```

**Comment by VeNoMouS** [comment]
ah actually db->count wont work... that change for this logic is from #583

**Comment by avbdr** [comment]
fixed in master. thank you
