### ISSUE TITLE
Creating a trigger with rawQuery

### ISSUE THREAD

**Issue by xeon826** [ThingEngineer/PHP-MySQLi-Database-Class#778]
```
$this->db->rawQuery('DELIMITER $$

CREATE TRIGGER inc_update
  AFTER UPDATE ON incoming
  FOR EACH ROW 
BEGIN
  UPDATE products
    SET inc = COALESCE(inc, 0) + NEW.NumReceived
    WHERE products.id = NEW.ProductId;
END;$$

DELIMITER ;');
```
Is this not possible?

**Comment by VeNoMouS** [comment]
What is the error you get? what does `$this->db->getLastQuery()` show?

**Comment by avbdr** [comment]
unfortunately mysqli prepared statements doesnt support create trigger command for some reason.

**Comment by xeon826** [comment]
Very well then. It is such that references to local variables are only permitted during stored program execution.
