### ISSUE TITLE
Non alpha-numeric characters unexpectedly stripped from ORDER BY field()

### ISSUE THREAD

**Issue by johnmap** [ThingEngineer/PHP-MySQLi-Database-Class#781]
This is where it's happening: https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/blob/db53256e86743e19c67f2c5dfa1b80557ecbd3f6/MysqliDb.php#L1180

I presume there's a reason for this (hence not just making a PR), but if that's a security/injection prevention reason, we could probably be less zealous.

In fact, is there a reason variables aren't being bound properly in this case? Happy to make a PR for this if it would help.

This is breaking queries like
```
$db->where('hanzi', array('我', '們'), 'IN');
$db->orderBy('hanzi', 'ASC', array('我', '們'));
$db->getValue(...
```

**Comment by avbdr** [comment]
thanks. PR merged into master
