### ISSUE TITLE
copy $db->where(); for another query

### ISSUE THREAD

**Issue by webnetbt** [ThingEngineer/PHP-MySQLi-Database-Class#787]
How to copy all where for another "get"?

$db->where ('category', $wherecatina[0]);
$db->where('category', Array($wherecatin), 'IN');
$count = $db->getValue('torrents','count(*)');
need copy all top "where" for next query -
$cols = Array("torrents.id", "torrents.times_completed", "torrents.owner");
$res = $db->get('torrents',Array($lim_in,$lim_out),$col);
How it`s possible?

**Comment by VeNoMouS** [comment]
god damn your code is nasty..

```
$db->where('category', $wherecatina[0]).where('category', [$wherecatin], 'IN').getValue('torrents', 'count(*)');
```

```
$db->where('category', $wherecatina[0]).where('category', [$wherecatin], 'IN').get(
    'torrents', 
     [
          $lim_in,
          $lim_out
     ],
     [
         'torrents.id',
         'torrents.times_completed',
         'torrents.owner'
     ]
);
```

**Comment by webnetbt** [comment]
Oh,, I found problem in connection with mysql server, so when i tired $db-copy(); get error. Now all fine.
