### ISSUE TITLE
Version 1 ugprade to current version.

### ISSUE THREAD

**Issue by KmanProdz** [ThingEngineer/PHP-MySQLi-Database-Class#806]
Although I'm still using Version 1.1 from around 2013 with MariaDB v10 (lol) if I was mean't to take the leap and install the new version of today, would I need to change how my current db code operates or will it still all be compatible. I only use basic methods: connect, where, get, getOne, myRawQuery, query, insert, update and delete that's it. Thanks.

**Comment by InkedCurtis** [comment]
`myRawQuery` was a function I added myself to a very old system of mine that you're still using the class from lol
