### ISSUE TITLE
How to connect using ssl cert

### ISSUE THREAD

**Issue by lincolnaleixo** [ThingEngineer/PHP-MySQLi-Database-Class#810]
I have a mysql server that are using ssl key,cert and server ca. How can I make the connection with the files needed?

I tried this but couldn't connect:
```
$conn = new MysqliDb (getenv('DB_CLOUD_SERVERNAME'), getenv('DB_CLOUD_USERNAME'), getenv('DB_CLOUD_PASSWORD'), getenv('DB_LOCAL_NAME'));
mysqli_ssl_set($conn->mysqli(), 'client-key.pem', 'client-cert.pem', 'server-ca.pem', null, null);
```

Thanks

**Comment by mbdmt** [comment]
try it
find  connect() function:
Replace some code

        if (empty($this->host)) {
            throw new Exception('MySQL host is not set');
        }
/*----- here start ----*/

        if(SYS_DBSSL_ON=='1'){
            $this->_mysqli = mysqli_init();
            $this->_mysqli->ssl_set(NULL, NULL, HERE_SSL_CERT_PATH, NULL, NULL);
            $this->_mysqli->real_connect($this->host, $this->username, $this->password, $this->db, $this->port, NULL ,MYSQLI_CLIENT_SSL);
        }else{
            $this->_mysqli = new mysqli($this->host, $this->username, $this->password, $this->db, $this->port);
        }

/*----- here end----*/

        if ($this->_mysqli->connect_error) {
            throw new Exception('Connect Error ' . $this->_mysqli->connect_errno . ': ' . $this->_mysqli->connect_error, $this->_mysqli->connect_errno);
        }
