### ISSUE TITLE
Can you help in a simple query?

### ISSUE THREAD

**Issue by Jazzykhan** [ThingEngineer/PHP-MySQLi-Database-Class#815]
Hi, Currently it returns me true or false from the column "IAP"
`$Check = $db->rawQueryValue ('select IAP from checkiap where ID=? limit 1', Array(1));`
I want to make it false if it is true and make it true if it false?
this is my button code:
<a href=""  class="btn btn-danger delete_btn"  style="margin-right: 8px;"><span class="glyphicon glyphicon-ban-circle"></span></a>
this is how i echo
`<td><?php echo $Check; ?></td>`
Thanks

**Comment by abdalmonem** [comment]
in "logic" if you say "NOT TRUE" its mean "false"
so you can try : 
`<td><?php echo !$Check; ?></td>`

**Comment by Coinizy1** [comment]
no no i want a query by which i can update the opposite value in my table lol
like if it is true now i want to make it false. it is not a bool (column) it is a varchar field
thanks

**Comment by satalways** [comment]
You can try something like this.

`$db->rawQuery('UPDATE table_name SET column_name = NOT column_name WHERE id=?', array(1))`

and if you want to check that query works fine then use these codes
`if ($db->getLastErrno()<>0) echo $db->getLastError();`
