### ISSUE TITLE
How to upload images?

### ISSUE THREAD

**Issue by berkanaslan** [ThingEngineer/PHP-MySQLi-Database-Class#851]
How to upload images with html form type = files?

**Comment by siberfx** [comment]
Bununla alakalı değil :)

**Comment by berkanaslan** [comment]
Soru mu repo mu? :) db'ye insert data soruyorum sonucta:/

**Comment by siberfx** [comment]
image manipülasyon icin verot.net upload.class.php tavsiye ederim, kayit
işlemide başarılı upload ardından kayit yapabilirsin

**Comment by berkanaslan** [comment]
her iki class arası çakışma olmaz umarım; deneyeceğim

**Comment by siberfx** [comment]
Olmaz rahat ol

**Comment by darkcavalry** [comment]
servera imaj upload edip db'ye mi yazdırmak istiyorsun yoksa imaj dosyasını blob türevi db üzerinde mi saklamak istiyorsun?

**Comment by berkanaslan** [comment]
yep, server'a upload etmek istiyordum. @siberfx'in önerdiği upload.class.php ile çalışarak halletim.

**Comment by siberfx** [comment]
I'm glad that it helped you out

**Comment by Cyberfolks** [comment]
can you please explain it in english... i want to upload image.

**Comment by Cyberfolks** [comment]
can you please share your code.
add/edit files and form..
i have created 4 fields and 1 image field.
text data is passing from customers-form.php as in project. but cant understand how to add image.
thanks in advance...

**Comment by siberfx** [comment]
what are you trying to do, share some code sample please @Cyberfolks

**Comment by Cyberfolks** [comment]
thank you for reply bro.
look
i want to upload image on server. and save image path/name.ext on database table.
its working fine without image. but i want to upload image.
here is my form code:
<form class="form" action="" method="post" id="group_form" enctype="multipart/form-data">
        <fieldset>
            <div class="form-group">
                <label for="g_name">Group Name *</label>
                <input type="text" name="g_name" value="<?php echo htmlspecialchars($edit ? $customer['g_name'] : '', ENT_QUOTES, 'UTF-8'); ?>" placeholder="Group Name" class="form-control" required="required" id = "g_name">
            </div> 
            <div class="form-group">
                <label for="g_desc">Group Description</label>
                <textarea name="g_desc" placeholder="Group Description" class="form-control" id="g_desc"><?php echo htmlspecialchars(($edit) ? $customer['g_desc'] : '', ENT_QUOTES, 'UTF-8'); ?></textarea>
            </div>
            <div class="form-group">
                <label for="g_link">Group Link</label>
                <input type="text" name="g_link" placeholder="Group Link" class="form-control" id="g_link" value="<?php echo htmlspecialchars($edit ? $customer['g_link'] : '', ENT_QUOTES, 'UTF-8'); ?>">
            </div>
            <div class="form-group">
                <label for="g_image">Group Image</label>
                <input type="file" name="g_image" class="form-control" id="g_image">
            </div>
            <div class="form-group text-center">
                <label></label>
                <button type="submit" name="submit" class="btn btn-warning" >Add Group <i class="glyphicon glyphicon-send"></i></button>
            </div>
        </fieldset>
    </form>

**Comment by Cyberfolks** [comment]
here is add_group.php file code

`<?php
session_start();
require_once 'config/config.php';
require_once BASE_PATH.'/includes/auth_validate.php';


// Serve POST method, After successful insert, redirect to customers.php page.

if ($_SERVER['REQUEST_METHOD'] === 'POST') 
{
    // Mass Insert Data. Keep "name" attribute in html form same as column name in mysql table.
    $data_to_db = array_filter($_POST);

    // Insert user and timestamp
    $data_to_db['created_by'] = $_SESSION['user_id'];
    $data_to_db['created_at'] = date('Y-m-d H:i:s');

    // Check if image file is a actual image or fake image
    $db = getDbInstance();
    $last_id = $db->insert('groups', $data_to_db);

    if ($last_id)
    {
        $_SESSION['success'] = 'Group added successfully!';
        // Redirect to the listing page
        header('Location: groups.php');
        // Important! Don't execute the rest put the exit/die.
        exit();
    }
    else
    {
        echo 'Insert failed: ' . $db->getLastError();
        exit();
    }
    
}

// We are using same form for adding and editing. This is a create form so declare $edit = false.
$edit = false;
?>
<?php include BASE_PATH.'/includes/header.php'; ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Add Group</h2>
        </div>
    </div>
    
    <?php include BASE_PATH.'/includes/flash_messages.php'; ?>
    <form class="form" action="" method="post" id="group_form" enctype="multipart/form-data">
    <?php include BASE_PATH.'/forms/group_form.php'; ?>
    </form>
</div>
<script type="text/javascript">
$(document).ready(function(){
   $('#group_form').validate({
       rules: {
            g_name: {
                required: true,
                minlength: 5
            },
            g_link: {
                required: true,
                minlength: 3
            }, 
            g_desc: {
                required: true,
                minlength: 3
            },   
        }
    });
});
</script>
<?php include BASE_PATH.'/includes/footer.php'; ?>`

**Comment by siberfx** [comment]
[https://www.verot.net/php_class_upload.htm?lang=en-GB](url) check this link, it shwos you examples of uploading. there are many different options, like resizing on upload, thumbnails, crop, ... etc.

**Comment by siberfx** [comment]
just download class.upload.php and include it to your code.

**Comment by Cyberfolks** [comment]
i need your kind guidelines.  im new in php..
we are receiving data from Group-forms.php inside add_group.php ok.
<form class="form" action="" method="post" id="group_form" enctype="multipart/form-data">
in this line we dont have any form action.
and processing from same file "add_group.php" to save in database. so what i can do for this.
if i add class.upload.php in side form action so how can pass image path to database query.
hope you understand what im trying to say.
thanks in advance....

**Comment by siberfx** [comment]
give me the file which is processing the database saving operation, I do changes and send you back.

**Comment by Cyberfolks** [comment]
ok sending you all files code here

Add-group.php (Added Form Inside file.)
`<?php
session_start();
require_once 'config/config.php';
require_once BASE_PATH.'/includes/auth_validate.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') 
    $data_to_db = array_filter($_POST);
    $data_to_db['created_by'] = $_SESSION['user_id'];
    $data_to_db['created_at'] = date('Y-m-d H:i:s');
    $db = getDbInstance();
    $last_id = $db->insert('groups', $data_to_db);

    if ($last_id)
    {
        $_SESSION['success'] = 'Group added successfully!';
        header('Location: groups.php');
        exit();
    }
    else
    {
        echo 'Insert failed: ' . $db->getLastError();
        exit();
    }
    
}
$edit = false;
?>
<?php include BASE_PATH.'/includes/header.php'; ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">Add Group</h2>
        </div>
    </div>
    <?php include BASE_PATH.'/includes/flash_messages.php'; ?>
    <form class="form" action="" method="post" id="group_form" enctype="multipart/form-data">
        <fieldset>
            <div class="form-group">
                <label for="g_name">Group Name *</label>
                <input type="text" name="g_name" value="<?php echo htmlspecialchars($edit ? $customer['g_name'] : '', ENT_QUOTES, 'UTF-8'); ?>" placeholder="Group Name" class="form-control" required="required" id = "g_name">
            </div> 
            <div class="form-group">
                <label for="g_desc">Group Description</label>
                <textarea name="g_desc" placeholder="Group Description" class="form-control" id="g_desc"><?php echo htmlspecialchars(($edit) ? $customer['g_desc'] : '', ENT_QUOTES, 'UTF-8'); ?></textarea>
            </div>
            <div class="form-group">
                <label for="g_link">Group Link</label>
                <input type="text" name="g_link" placeholder="Group Link" class="form-control" id="g_link" value="<?php echo htmlspecialchars($edit ? $customer['g_link'] : '', ENT_QUOTES, 'UTF-8'); ?>">
            </div>
            <div class="form-group">
                <label for="g_image">Group Image</label>
                <input type="file" name="g_image" class="form-control" id="g_image">
            </div>
            <div class="form-group text-center">
                <label></label>
                <button type="submit" name="submit" class="btn btn-warning" >Add Group <i class="glyphicon glyphicon-send"></i></button>
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
$(document).ready(function(){
   $('#group_form').validate({
       rules: {
            g_name: {
                required: true,
                minlength: 5
            },
            g_link: {
                required: true,
                minlength: 3
            }, 
            g_desc: {
                required: true,
                minlength: 3
            },   
        }
    });
});
</script>
<?php include BASE_PATH.'/includes/footer.php'; ?>
`

**Comment by darkcavalry** [comment]
Use this function for global uploads.

```
function uploader($file,$saveto,$name=''){
    include_once('class.upload.php');
    $result = array('error'=>true,'text'=>'Error occured','file_name'=>'');
    $handle = new upload($_FILES[$file]);
    if($handle->uploaded) {
        if($name!='){
            $handle->file_new_name_body = $name;
        }
        $handle->process($saveto);
        if ($handle->processed) {
            $result['error'] = false;
            $result['text'] = 'Image uploaded';
            $result['file_name'] = $handle->file_dst_name;
            $handle->clean();
        }else{
            $result['text'] = $handle->error;
        }
    }else{
        $result['text'] = $handle->error;
    }

    return $result;
}
```
function variables

@file = form file input name
@saveto = path of upload directory
@name = new file name if you want to rename uploaded file

Integration on your group creation code

```
if ($last_id)
{
    $upl = uploader('g_image','/path/to/','my_file');
    if($upl['error']==false){
        $db->where('group_id=?',array($last_id))->update('groups',array('image_column'=>$upl['file_name']));
    }
    $_SESSION['success'] = 'Group added successfully!';
    header('Location: groups.php');
    exit();
}
```

You can use this function globally, also its just a example there too many options available on verot uploader class as @siberfx said.

Above integration upload after group creation, you can control uploaded file before insert, the correct method will be that way.

**Comment by Cyberfolks** [comment]
hi @darkcavalry  thank you very much dear for your detailed solution. i really appreciate it.

but i just use this way to upload image.

`if(isset($_POST['submit'])){
    if(isset($_FILES['g_image'])){
        $img = $_FILES["g_image"]["tmp_name"];
        $image = $_FILES['g_image']['name'];
        $target = "uploads/".basename($image);
        $imageFileType = strtolower(pathinfo($target,PATHINFO_EXTENSION));
        if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg" && $imageFileType != "gif" ) {
//Add Your error message here
        }else{
            move_uploaded_file($_FILES['g_image']['tmp_name'], $target);
            $data = [
                'g_name' => $_POST['g_name'],
                'g_desc' => $_POST['g_desc'],
                'g_link' => $_POST['g_link'],
                'g_image' => $targert,
            ];
            $data['created_by'] = $_SESSION['user_id'];
            $data['created_at'] = date('Y-m-d H:i:s');
            print_r($data);
            $db = getDbInstance();
            $last_id = $db->insert('groups', $data);
            if ($last_id)
            {
                $_SESSION['success'] = 'Group added successfully!';
                header('Location: groups.php');
                exit();
            }
            else
            {
            echo 'Insert failed: ' . $db->getLastError();
                exit();
            }
        }
    }
}`

**Comment by peixespnsc** [comment]
Hi folks,
@Cyberfolks is using this repo https://github.com/chetans9/core-php-admin-panel, wich uses this MySQLi library.
I've made a fork here https://github.com/peixespnsc/core-php-admin-panel. If someone implement this, I'll merge it.

Thanks!

**Comment by darkcavalry** [comment]
@Cyberfolks uploader class already check file types, sizes etc. You no need to check extension. Just check file input file. Use my function insead;

```
if(isset($_POST['submit'])){ 
    if(isset($_FILES['g_image'])){ 
        $allowed = ['image/jpeg','image/gif','image/png']; # or just enter image/*
        $upl = uploader('g_image','uploads/','new_name',$allowed);
        if($upl==false){
            # Uploaded successfully
            $data = [ 'g_name' => $_POST['g_name'], 'g_desc' => $_POST['g_desc'], 'g_link' => $_POST['g_link'], 'g_image' => $upl['file_name'] ]; 
            $data['created_by'] = $_SESSION['user_id']; 
            $data['created_at'] = date('Y-m-d H:i:s'); 
            $last_id = $db->insert('groups', $data); 
            if ($last_id) { 
                $_SESSION['success'] = 'Group added successfully!'; 
                header('Location: groups.php'); exit(); 
            }else{
                echo 'Insert failed: ' . $db->getLastError(); exit(); 
            }
        }else{
            echo($upl['text']); # error output
        }
    }else{
        echo('Please choose a image file');
    } 
}
```

and change my function 

```
function uploader($file,$saveto,$name='',$types=array()){
    include_once('class.upload.php');
    $result = array('error'=>true,'text'=>'Error occured','file_name'=>'');
    $handle = new upload($_FILES[$file]);
    $handle->file_overwrite = false;
    $handle->file_auto_rename = true;
    # $handle->file_max_size = '1024'; // 1KB -- if you want to check maximum file size enter a value as byte 
    if(count($types)>0){
        $handle->allowed = $types;
    }
    if($handle->uploaded) {
        if($name!='){
            $handle->file_new_name_body = $name;
        }
        $handle->process($saveto);
        if ($handle->processed) {
            $result['error'] = false;
            $result['text'] = 'Image uploaded';
            $result['file_name'] = $handle->file_dst_name;
            $handle->clean();
        }else{
            $result['text'] = $handle->error;
        }
    }else{
        $result['text'] = $handle->error;
    }

    return $result;
}
```
There too many options available, you can customize uploader function https://github.com/verot/class.upload.php/blob/master/README.md

**Comment by Cyberfolks** [comment]
hi @darkcavalry  i never used this class.upload.php.
i have uploaded image simply using php class.

i just check if _FILE is available so.
checking:
$img = $_FILES["g_image"]["tmp_name"];  file temp name.
$image = $_FILES['g_image']['name'];  file name.
$target = "uploads/".basename($image);  creating path with folder.
$imageFileType = strtolower(pathinfo($target,PATHINFO_EXTENSION));
if($imageFileType != "jpg" && $imageFileType != "png" && $imageFileType != "jpeg" && $imageFileType != "gif" ) { Do something }  checking file ext for security reasons.
and in else simply move image to directory
move_uploaded_file($_FILES['g_image']['tmp_name'], $target);
and simply push data to database with
$data = array_filter($_POST);
            $data['created_by'] = $_SESSION['user_id'];
            $data['g_image'] = $target;
            $data['created_at'] = date('Y-m-d H:i:s');
            print_r($data);
            $db = getDbInstance();
            $last_id = $db->insert('groups', $data);
            if ($last_id)
            {
                $_SESSION['success'] = 'Group added successfully!';
                header('Location: groups.php');
                exit();
            }
            else
            {
            echo 'Insert failed: ' . $db->getLastError();
                exit();
            }

so no need to use any extra file.. you can add more functions to check size, image resize or base64 what ever you want.
but in my case i dont want these type of functions. so push simple image
