### ISSUE TITLE
How to structure array on Update

### ISSUE THREAD

**Issue by juanantoniotv** [ThingEngineer/PHP-MySQLi-Database-Class#852]
Hi how is the array structure on Update function, for example if I have on my table many columns (price1, price2, price3, price4) and I want update price3 same that price1.

> //This form I have error
> $data = (
>    'price3' => $db->price1 
> );

> //This form I also have error
> $data = (
>    'price3' => 'price1' 
> );

**Comment by myEric** [comment]
Hi,
I think you should define value outside the array. 
$price1 = some value;

$data = [
‘price1´ => $price1,
price3´ => $price1,
.....
];

**Comment by juanantoniotv** [comment]
> Hi,
> I think you should define value outside the array.
> $price1 = some value;
> 
> $data = [
> ‘price1´ => $price1,
> price3´ => $price1,
> .....
> ];

Can I do it, but first I have to get the value of price1 in a query, but i have around 6 millons of records and many queries running! hahaha no more queries!

**Comment by myEric** [comment]
With a large dataset you are not doing the right way. Consider something like

$db->rawQuery("UPDATE table1 t1, table2 t2 SET t1.column1 = t2.colum2 WHERE t1.id = t2.id");

It will take one or 2 seconds to run and update all rows. Try and let me know. I tested on 25k rows

**Comment by juanantoniotv** [comment]
I'm solved my question, I used rawQueryone function:

> $db->rawQueryOne ('UPDATE sms_billing SET price3 = price1 WHERE id = ? LIMIT 1', Array(90284283));
> if ($db->count > 0){
>    echo "Record updated.";
> }

Have a nice day!

**Comment by juanantoniotv** [comment]
> With a large dataset you are not doing the right way. Consider something like
> 
> $db->rawQuery("UPDATE destination table dt, source table st SET dt.column1 = st.colum WHERE dt.id = st.id");
> 
> Update the where clause to fit your needs. It will take one or 2 seconds to run and update all rows. Try and let me know. I tested on 25k rows

But is over the same table.
