### ISSUE TITLE
query with multiple or

### ISSUE THREAD

**Issue by pigiakeys** [ThingEngineer/PHP-MySQLi-Database-Class#863]
Hi, 
I need to do a query like:
SELECT * FROM aggiornanonconf2019 WHERE Provenienza = 'Esterna' AND (TipoSegn like '%rosapetra%' OR RagSociale like '%rosapetra%' OR Oggetto like '%rosapetra%').
I tried using:

> $db->where ('Provenienza', 'Esterna');
> $db->orWhere ("(Oggetto like '%?%' or RagSociale like '%?%' or TipoSegn = '%?%')", Array($key_search,$key_search));

but it is wrong.
how could I do?
thanks

**Comment by adrianlaraperez88** [comment]
Hi @pigiakeys, try this:
`$db->where ('Provenienza', 'Esterna');
$db->Where ("(Oggetto like '%?%' or RagSociale like '%?%' or TipoSegn = '%?%')", Array($key_search,$key_search) );`

**Comment by pigiakeys** [comment]
Hi, @adrianlaraperez88 
thanks for your suggestion but it doesn't work.

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in /customers/e/5/5/customerservice-lm2000srl.it/httpd.www/ricerche/query/include/MysqliDb.php on line 1445 SELECT * FROM aggiornanonconf2019 WHERE Provenienza = 'Esterna' AND (idSegn like '%'rosapetra'%' or TipoSegn = '%'rosapetra'%' or RagSociale = '%'rosapetra'%' or Oggetto = '%'rosapetra'%' or Note = '%'rosapetra'%' or Stato = '%'rosapetra'%') ORDER BY id DESC

this is what I wrote:

$db->Where ('Provenienza', 'Esterna');
$db->Where ("(idSegn like '%?%' or TipoSegn = '%?%' or RagSociale = '%?%' or Oggetto = '%?%' or Note = '%?%' or Stato = '%?%')", Array($key_search,$key_search,$key_search,$key_search,$key_search,$key_search));

**Comment by pigiakeys** [comment]
I found a solution, I don't know if it's the best solution but it works

```
> $db->Where ('Provenienza', 'Esterna');
> $db->Where ("(idSegn like ? or TipoSegn like ? or RagSociale like ? or Oggetto like ? or Note like ? or Stato like ?)", Array("%" . $key_search . "%","%" . $key_search . "%","%" . $key_search . "%","%" . $key_search . "%","%" . $key_search . "%","%" . $key_search . "%"));
```
that gives me:

`SELECT * FROM aggiornanonconf2019 WHERE Provenienza = 'Esterna' AND (idSegn like '%rosapetra%' or TipoSegn like '%rosapetra%' or RagSociale like '%rosapetra%' or Oggetto like '%rosapetra%' or Note like '%rosapetra%' or Stato like '%rosapetra%') ORDER BY id DESC`
