### ISSUE TITLE
How I can use case condition with order by statement.

### ISSUE THREAD

**Issue by vikramsingh86** [ThingEngineer/PHP-MySQLi-Database-Class#888]
I am trying to fetch records by ordering them according to different fields. I need to use case clause with in order by statement. How I can use it. Please suggest.

**Comment by darkcavalry** [comment]
you can use multiple orderBy in your query.

`$rs = $db->orderBy('user_name','ASC')->orderBy('user_created','DESC')->get('users');`

**Comment by vikramsingh86** [comment]
Hi @darkcavalry ,

Thanks for your answer. Actually I want to use CASE WHEN statement in ORDER BY clause.
For example:
ORDER BY 
CASE WHEN Column1 <> 0 THEN Column1 DESC ELSE ASC END

**Comment by darkcavalry** [comment]
Hi,

You can use Case statement in orderBy as same way. 

```
$rs = $db->orderBy('(CASE WHEN Column1 <> 0 THEN Column1 END)','DESC')
                ->orderBy('(CASE WHEN Column1 = 0 THEN Column1 END)','ASC')
                ->get('users');
```

**Comment by vikramsingh86** [comment]
Hi @darkcavalry ,

Thanks for your quick reply. It works perfectly. Thanks for your help.
