### ISSUE TITLE
after update to  php 7.3 Class mysqli does not exist

### ISSUE THREAD

**Issue by mohammeddawod** [ThingEngineer/PHP-MySQLi-Database-Class#914]
There is error after update server to php 7.3

Uncaught ReflectionException: Class mysqli does not exist in /home/test/public_html/inc/MysqliDb.php:322

**Comment by paul-stolk-webdiensten** [comment]
Which exact PHP version do you use? I don't have this issue with PHP 7.3.19 and class version 2.9.3

**Comment by jjasoncool** [comment]
please check your php.ini and open your ext.
