### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by paul-stolk-webdiensten** [ThingEngineer/PHP-MySQLi-Database-Class#916]
When getting records from the database, the PHP memory goes up drastically. 

````
( ! ) Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 2711347632 bytes) in /xxx/MysqliDb.php on line 1621
````

MySQLi class version 2.9.3. 

I have this on:
PHP Version 7.4.7
Mysqli version 10.3.8

I _dont_ have this on:
PHP Version 7.4.2
mysqlnd 7.4.2

I'm not sure the versions are related.

There are two get()'s on the page; the first goes ok. Right before the second time line 1621 is reached,  `memory_get_usage()` gives _1746944 bytes used_. When line 1621 is reached the allowed memory size is exhausted.

**Comment by fiberchains** [comment]
Did you find a solution?

**Comment by paul-stolk-webdiensten** [comment]
> Did you find a solution?

Sadly: no. In the end I just used standard mysqli queries without any framework/class.

**Comment by davvalent** [comment]
Maybe you'll find some clues there: #820 

Regards
