### ISSUE TITLE
Error: Malformed communication packet

### ISSUE THREAD

**Issue by itqan** [ThingEngineer/PHP-MySQLi-Database-Class#930]
When I am trying to use rawQuery function with no where condition I got this error:
"Malformed communication packet"

can anyone help me to fix this issue???

**Comment by xclntdesign** [comment]
A MariaDB update seems to be causing this issue.

https://forums.cpanel.net/threads/mariadb-10-3-26-1-breaks-php-7-2.680989/

Upgrading your PHP to 7.3 or later fixes the issue.

**Comment by itqan** [comment]
xclntdesign .. unfortunately I cannot upgrade to PHP 7.x now while I have to remain on 5.6 due to code compatibility issues .. is there any other solutions to this error?

**Comment by xclntdesign** [comment]
If you have the access, cPanel recommends downgrading MariaDB until a fix is ready.

https://support.cpanel.net/hc/en-us/articles/360056772334

**Comment by Ton2800re** [comment]
I got same problem and I cant make changes to MariaDB. Is there any changes I can do to MysqliDb.php -script that helps?

**Comment by xclntdesign** [comment]
For each of your calls, you can add a WHERE statement that will also be true, like WHERE id > 0 or something like that.
