### ISSUE TITLE
empty array on server, but on localhost array is not empty

### ISSUE THREAD

**Issue by alenev** [ThingEngineer/PHP-MySQLi-Database-Class#933]
Hello. Please tell me why on localhost the data from the database is placed into an array, and on the server the array is empty.
1) On localhost (https://ospanel.io), the selection from the database table into the array occurs
```
$ users = $ db-> get (T_USERS);
echo 'users:' .count ($ users);
```
2) On the server (CentOS 7 + Cpanel) with this choice of an array with data, empty https://prnt.sc/vgsokv
3) But the data selection of one field from the database on the server is created https://prnt.sc/vgssne
```
$ email = $ db-> where ('user_id', 14) -> getValue (T_USERS, 'user_id');
echo 'user_id:'. $ email;
```

**Comment by mrokkada** [comment]
encountering similar issue. Inserts are working fine.  But select statements are fetching empty result set even though data is present in the backend.

**Comment by oxcakmak** [comment]
I am encountering the same error with the latest version. Can anyone find a solution?
