### ISSUE TITLE
Notice: Undefined offset: 0 on line 559

### ISSUE THREAD

**Issue by theveloperspl** [ThingEngineer/PHP-MySQLi-Database-Class#964]
Query below produces warning stated in issue title:
$db->rawQuery("SELECT user, usd_value, date, method FROM `deposits` ORDER BY `id` DESC LIMIT 5");
Warning is:
Notice: Undefined offset: 0 in C:\xampp\htdocs\investor\vendor\thingengineer\mysqli-database-class\MysqliDb.php on line 559

The warning is thrown but the query is successful and returns correct data.
Any idea on fixing this?

**Comment by Dibbyo456** [comment]
The main purpose of an wrapper is to **avoid** Raw SQL query.

**Comment by theveloperspl** [comment]
yeah, I managed to do this by built in functions

**Comment by fantasy99** [comment]
> 是的，我设法通过内置函数来做到这一点

        preg_match_all("/(from|into|update|join|describe) [\\'\\´]?([a-zA-Z0-9_-]+)[\\'\\´]?/i", $query, $matches);
        $_from_table=$_from=$_table='';
        list($from_table, $from, $table) = $matches;
        if (isset($table[0])) {
            $_table=$table[0];
        }
        return str_replace($_table, self::$prefix.$_table, $query);

**Comment by fantasy99** [comment]
> 下面的查询会产生问题标题中所述的警告：$db->rawQuery（“选择用户、usd_value、日期、方法从按 DESC 限制 5 排序”）;警告是： 注意：未定义的偏移量：0 在 C：\xampp\htdocs\investor\vendor\thingengineer\mysqli-database-class\MysqliDb.php 在第 559 行`deposits``id`
> 
> 引发警告，但查询成功并返回正确的数据。有什么想法可以解决这个问题吗？

fix method rawAddprefix() in file mysqlidb.php
        preg_match_all("/(from|into|update|join|describe) [\\'\\´]?([a-zA-Z0-9_-]+)[\\'\\´]?/i", $query, $matches);
        $_from_table=$_from=$_table='';
        list($from_table, $from, $table) = $matches;
        **if (isset($table[0])) {
            $_table=$table[0];
        }**
        return str_replace($_table, self::$prefix.$_table, $query);

**Comment by fantasy99** [comment]
> Query below produces warning stated in issue title: $db->rawQuery("SELECT user, usd_value, date, method FROM `deposits` ORDER BY `id` DESC LIMIT 5"); Warning is: Notice: Undefined offset: 0 in C:\xampp\htdocs\investor\vendor\thingengineer\mysqli-database-class\MysqliDb.php on line 559
> 
> The warning is thrown but the query is successful and returns correct data. Any idea on fixing this?

edit method rawAddprefix() in file mysqlidb.php
`preg_match_all("/(from|into|update|join|describe) [\'\´]?([a-zA-Z0-9_-]+)[\'\´]?/i", $query, $matches);
**$_from_table=$_from=$_table='';**
list($from_table, $from, $table) = $matches;
**if (isset($table[0])) {
$_table=$table[0];
}**
return str_replace($_table, self::$prefix.$_table, $query);`

**Comment by fantasy99** [comment]
> Query below produces warning stated in issue title: $db->rawQuery("SELECT user, usd_value, date, method FROM `deposits` ORDER BY `id` DESC LIMIT 5"); Warning is: Notice: Undefined offset: 0 in C:\xampp\htdocs\investor\vendor\thingengineer\mysqli-database-class\MysqliDb.php on line 559
> 
> The warning is thrown but the query is successful and returns correct data. Any idea on fixing this?

edit method rawAddprefix() in file mysqlidb.php
    public function rawAddPrefix($query){
        $query = str_replace(PHP_EOL, '', $query);
        $query = preg_replace('/\s+/', ' ', $query);
        preg_match_all("/(from|into|update|join|describe) [\\'\\´]?([a-zA-Z0-9_-]+)[\\'\\´]?/i", $query, $matches);
        **$_from_table=$_from=$_table='';**
        list($from_table, $from, $table) = $matches;
        **if (isset($table[0])) {
            $_table=$table[0];
        }**
        return str_replace($_table, self::$prefix.$_table, $query);
    }
