### ISSUE TITLE
Is rollback() available in 5.3?

### ISSUE THREAD

**Issue by ZhangChengLin** [ThingEngineer/PHP-MySQLi-Database-Class#974]
https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/blob/16564ba0717fad64617a1ce4a8d3f9b90e68c7c2/MysqliDb.php#L2303

https://github.com/ThingEngineer/PHP-MySQLi-Database-Class/blob/16564ba0717fad64617a1ce4a8d3f9b90e68c7c2/composer.json#L20

Is rollback() available in 5.3?

**Comment by RyadPasha** [comment]
Yes, it's available on PHP 5+
[PHP: mysqli::rollback - Manual](https://www.php.net/manual/en/mysqli.rollback.php)
