### ISSUE TITLE
Data return from views in hosting

### ISSUE THREAD

**Issue by bdj-Razik** [ThingEngineer/PHP-MySQLi-Database-Class#978]
hey
My problem is when I run the syntax ** $db->get(view_name); **
   It returns an empty table but when I use 
$db->tableExist(view_name) return true
** and ** my connection to the database is successful
Please I need help because I have more than 51 views

**Comment by forwhat461** [comment]
can you  get other tables or views?
only this view returns empty table?
or check that view,make sure it's not empty?
