### ISSUE TITLE
php 8.1 - PHP Deprecated:  str_replace(): Passing null to parameter #2

### ISSUE THREAD

**Issue by mvander** [ThingEngineer/PHP-MySQLi-Database-Class#984]
PHP Deprecated:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in MysqliDb.php on line 554

`554       $query = str_replace(PHP_EOL, null, $query);`

**Comment by JuneTwooo** [comment]
please push the update :3
